# Upload exported FBX meshes to Roblox via Open Cloud Assets API, then regenerate
# src/shared/MeshAssets.luau with the resulting asset ids.
#   python tools/roblox_upload.py            # uploads everything new in assets/export
#   python tools/roblox_upload.py hoverboard # upload one
# Needs in .env:  ROBLOX_API_KEY (Open Cloud key with assets:read,assets:write)
#                 ROBLOX_USER_ID (numeric, from your roblox profile URL)

import json
import mimetypes
import os
import pathlib
import sys
import time
import urllib.request
import uuid

ROOT = pathlib.Path(__file__).resolve().parent.parent
EXPORT = ROOT / "assets" / "export"
IDMAP = ROOT / "assets" / "asset_ids.json"
LUAU = ROOT / "src" / "shared" / "MeshAssets.luau"


def load_env():
    env_file = ROOT / ".env"
    if env_file.exists():
        for line in env_file.read_text().splitlines():
            line = line.strip()
            if line and not line.startswith("#") and "=" in line:
                key, value = line.split("=", 1)
                os.environ.setdefault(key.strip(), value.strip())


def multipart(fields, file_field, file_path):
    boundary = uuid.uuid4().hex
    body = b""
    for name, value in fields.items():
        body += (f"--{boundary}\r\nContent-Disposition: form-data; name=\"{name}\"\r\n\r\n{value}\r\n").encode()
    ctype = mimetypes.guess_type(str(file_path))[0] or "model/fbx"
    body += (
        f"--{boundary}\r\nContent-Disposition: form-data; name=\"{file_field}\"; "
        f"filename=\"{file_path.name}\"\r\nContent-Type: {ctype}\r\n\r\n"
    ).encode()
    body += file_path.read_bytes() + f"\r\n--{boundary}--\r\n".encode()
    return body, f"multipart/form-data; boundary={boundary}"


def api(url, key, data=None, content_type=None, method=None):
    headers = {"x-api-key": key}
    if content_type:
        headers["Content-Type"] = content_type
    req = urllib.request.Request(url, data=data, headers=headers, method=method or ("POST" if data else "GET"))
    with urllib.request.urlopen(req) as response:
        return json.load(response)


def upload_one(name, key, user_id):
    fbx = EXPORT / f"{name}.fbx"
    request_payload = json.dumps({
        "assetType": "Model",
        "displayName": f"NeonArcana {name}",
        "description": "Neon Arcana game asset (Tripo pipeline)",
        "creationContext": {"creator": {"userId": user_id}},
    })
    body, ctype = multipart({"request": request_payload}, "fileContent", fbx)
    op = api("https://apis.roblox.com/assets/v1/assets", key, body, ctype)
    op_path = op.get("path") or op.get("operationId")
    print(f"[upload] {name}: operation {op_path}")
    for _ in range(60):
        time.sleep(3)
        status = api(f"https://apis.roblox.com/assets/v1/{op_path}", key)
        if status.get("done"):
            asset_id = status["response"]["assetId"]
            print(f"[upload] {name} -> assetId {asset_id}")
            return asset_id
    raise TimeoutError(f"{name}: operation never completed")


def write_luau(idmap):
    lines = ["--!strict", "-- AUTO-GENERATED by tools/roblox_upload.py — do not hand-edit.", "return {"]
    for name in sorted(idmap):
        lines.append(f"\t{name} = \"rbxassetid://{idmap[name]}\",")
    lines.append("}")
    LUAU.write_text("\n".join(lines) + "\n", encoding="ascii")
    print(f"[luau] wrote {LUAU} with {len(idmap)} entries")


def main():
    load_env()
    key = os.environ.get("ROBLOX_API_KEY")
    user_id = os.environ.get("ROBLOX_USER_ID")
    if not key or not user_id:
        sys.exit("Set ROBLOX_API_KEY and ROBLOX_USER_ID in .env (create.roblox.com/dashboard/credentials)")

    idmap = json.loads(IDMAP.read_text()) if IDMAP.exists() else {}
    only = sys.argv[1] if len(sys.argv) > 1 else None
    targets = [only] if only else [f.stem for f in EXPORT.glob("*.fbx")]

    for name in targets:
        if name in idmap:
            print(f"[skip] {name} already uploaded ({idmap[name]})")
            continue
        try:
            idmap[name] = upload_one(name, key, int(user_id))
            IDMAP.write_text(json.dumps(idmap, indent=2))
        except Exception as error:  # keep going; report at end
            print(f"[FAIL] {name}: {error}")

    write_luau(idmap)


if __name__ == "__main__":
    main()
